apiVersion: apps/v1
kind: Deployment
metadata:
 name: workerpodcustomautoscaler
 namespace: kube-system
 labels:
   app: workerpodcustomautoscaler
spec:
 replicas: 1
 selector:
   matchLabels:
     app: workerpodcustomautoscaler
 template:
   metadata:
     labels:
       app: workerpodcustomautoscaler
   spec:
     serviceAccountName: workerpodcustomautoscaler
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     containers:
     - name: wpca
       env:
       - name: AWS_ACCESS_KEY_ID
         value: {{ WPA_AWS_ACCESS_KEY_ID }}
       - name: AWS_SECRET_ACCESS_KEY
         value: {{ WPA_AWS_SECRET_ACCESS_KEY }}
       image: 261701980167.dkr.ecr.us-east-1.amazonaws.com/k8s-worker-pod-autoscaler/workerpodautoscaler:{{ WPA_TAG }}
       imagePullPolicy: Always
       command:
       - /workerpodautoscaler
       - run
       - --resync-period=20
       - --wpa-threads=10
       - --aws-regions={{ WPA_AWS_REGIONS }}
       - --sqs-short-poll-interval=20
       - --sqs-long-poll-interval=20
       - --k8s-api-qps=5.0
       - --k8s-api-burst=10
       - --wpa-default-max-disruption=100%
       - --queue-services=sqs
       - -v=2
       resources:
         limits:
           cpu: 100m
           memory: 100Mi
         requests:
           cpu: 10m
           memory: 20Mi
