apiVersion: apps/v1
kind: Deployment
metadata:
 name: workerpodcustomautoscaler
 namespace: kube-system
 labels:
   app: workerpodcustomautoscaler
spec:
 replicas: 1
 selector:
   matchLabels:
     app: workerpodcustomautoscaler
 template:
   metadata:
     labels:
       app: workerpodcustomautoscaler
   spec:
     serviceAccountName: workerpodcustomautoscaler
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     containers:
     - name: wpca
       env:
       - name: AWS_ACCESS_KEY_ID
         value: {{ WPA_AWS_ACCESS_KEY_ID }}
       - name: AWS_SECRET_ACCESS_KEY
         value: {{ WPA_AWS_SECRET_ACCESS_KEY }}
       image: clearskyfish/k8s-worker-pod-custom-autoscaler:{{ WPA_TAG }}
       imagePullPolicy: Always
       command: ["sleep", "3600"]
       resources:
         limits:
           cpu: 100m
           memory: 100Mi
         requests:
           cpu: 10m
           memory: 20Mi
