apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: workerpodautoscalermultiqueue
  name: workerpodautoscalermultiqueue
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: workerpodautoscalermultiqueue-metrics
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: workerpodautoscalermultiqueue
  sessionAffinity: None
  type: ClusterIP
