apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: workerpodcustomautoscaler
  name: workerpodcustomautoscaler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: workerpodcustomautoscaler-metrics
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: workerpodcustomautoscaler
  sessionAffinity: None
  type: ClusterIP
